<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - ExamplesTest</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>ExamplesTest</h1>
<p>
  Test duration: 0.037s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">ExamplesTest</td>
      </tr>
            
<tr>
  <td class="method">
                  testDivision
      </td>
  <td class="duration">
    0.001s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">5, 0, 0</span><br />
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.ArithmeticException</b></a><br />
    <div class="stackTrace" id="exception-0">
              com.example.Cal.testDivision(Cal.java:7)<br />
              ExamplesTest.testDivision(ExamplesTest.java:48)<br />
              java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)<br />
              java.base/java.lang.reflect.Method.invoke(Method.java:580)<br />
              org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)<br />
              org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)<br />
              org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)<br />
              org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)<br />
              org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br />
              org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)<br />
              java.base/java.lang.Thread.run(Thread.java:1583)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  testDivisionWithException
      </td>
  <td class="duration">
    0.001s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">5, 5, 1</span><br />
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>org.testng.TestException: <br/>
Method ExamplesTest.testDivisionWithException(double,double,double)[pri:0, instance:ExamplesTest@5ccddd20] should have thrown an exception of type class java.lang.ArithmeticException</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)<br />
              org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:873)<br />
              org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:731)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)<br />
              org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)<br />
              org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)<br />
              org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br />
              org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)<br />
              java.base/java.lang.Thread.run(Thread.java:1583)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  testDivisionWithException
      </td>
  <td class="duration">
    0.001s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">5, 5, 1</span><br />
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>org.testng.TestException: <br/>
Method ExamplesTest.testDivisionWithException(double,double,double)[pri:0, instance:ExamplesTest@5ccddd20] should have thrown an exception of type class java.lang.ArithmeticException</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)<br />
              org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:873)<br />
              org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:731)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)<br />
              org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)<br />
              org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)<br />
              org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br />
              org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)<br />
              java.base/java.lang.Thread.run(Thread.java:1583)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  testDivisionWithException
      </td>
  <td class="duration">
    0.013s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">10, 5, 2</span><br />
    
        

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>org.testng.TestException: <br/>
Method ExamplesTest.testDivisionWithException(double,double,double)[pri:0, instance:ExamplesTest@5ccddd20] should have thrown an exception of type class java.lang.ArithmeticException</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)<br />
              org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:873)<br />
              org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:731)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)<br />
              org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)<br />
              org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)<br />
              org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)<br />
              org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br />
              org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)<br />
              java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)<br />
              java.base/java.lang.Thread.run(Thread.java:1583)<br />
                </div>
      </td>
</tr>
      </table>


  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">ExamplesTest</td>
      </tr>
            
<tr>
  <td class="method">
                  testDivision
      </td>
  <td class="duration">
    0.007s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">5, 5, 1</span><br />
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  testDivision
      </td>
  <td class="duration">
    0.013s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">10, 5, 2</span><br />
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  testDivision
      </td>
  <td class="duration">
    0.001s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">5, 5, 1</span><br />
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  testDivisionWithException
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
          <i>Method arguments: </i><span class="arguments">5, 0, 0</span><br />
    
        

      </td>
</tr>
      </table>
  
</body>
</html>
